
#line 2 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[668] =
    {   0,
        0,    0,  100,   98,   97,   97,   91,   98,   98,   98,
       98,   98,   94,   86,   98,   84,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   97,   83,   89,    0,   95,    0,
       96,   92,    0,    0,   94,   87,   82,   88,   85,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   93,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   78,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   55,    0,    0,    0,   71,    0,    0,    0,
        0,   56,    0,    0,    0,    0,    0,    0,    0,   65,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   68,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   49,    0,   50,    0,    0,    1,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   72,    0,    0,    0,
        0,    0,   10,    0,    0,    0,    0,   70,   16,    0,
        0,   61,    0,    0,    0,    0,    0,   25,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    0,    0,   54,    0,    0,   46,    0,
        0,    0,    0,    0,    0,    0,    0,   57,   28,    0,
       74,    0,    0,    0,   43,    0,    0,    0,    0,    0,
        0,   52,    0,   73,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   53,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   76,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,   59,    0,    0,    0,
        0,    0,    0,   11,   17,   60,    0,    0,    0,    0,
       26,    0,   77,    0,    0,   90,    0,    0,    0,    0,
       64,    0,    0,    0,    4,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,    0,    0,   62,    0,    0,    0,    0,    0,    0,
       40,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   66,
        0,    0,    0,    0,    0,    0,   47,    0,    0,   12,
       14,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,    0,    0,    0,    0,    0,    0,    0,    5,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   34,    0,    0,    0,    0,    0,   31,   32,
        0,    0,    0,    0,    0,   58,    0,    0,   33,   13,

       15,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   30,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,   69,   36,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   22,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   80,
        0,   79,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       80,    0,   79,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   23,   19,    0,    0,    0,

       67,    0,    0,    0,   48,    0,    0,    0,    0,    0,
       20,    0,    0,    0,    0,    0,   35,   81,   27,    0,
       51,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       81,    0,    0,    8,    0,    0,    0,    0,    0,   21,
        0,    0,    0,    0,   42,    0,    0,    0,    0,    0,
        6,    0,    0,    0,    9,    0,    0,   41,    0,    0,
        0,    0,   39,    7,   37,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    1,    1,    9,    1,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,   11,
       12,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,    1,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,   35,   36,
       37,   38,    1,   39,    1,   40,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[41] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[671] =
    {   0,
        0,    0,  683,  684,   39,   41,   33,  677,  678,  673,
      671,  669,  667,  664,   34,  663,   31,  655,   27,   31,
      640,  642,   38,   40,   41,   43,  642,   39,   44,   56,
       42,   49,   54,  631,   81,  684,  684,  664,  684,  665,
      684,  684,  659,   56,  656,  684,  684,  684,  684,  637,
      632,  638,  639,   75,  634,   65,  645,  642,  633,  629,
      625,  637,  626,  625,  637,   68,  624,  623,  623,  618,
      628,  619,   71,  613,  619,  611,   80,  619,  616,   82,
      609,  608,  606,  609,  607,   80,  612,  607,  603,  684,
      613,  598,  596,  606,  600,  602,  595,  594,  592,  608,

      598,  596,  596,  594,  585,  684,  599,  592,  588,  597,
      594,  589,  578,  587,  590,  582,  580,  684,  579,  588,
      571,  584,  588,  583,  565,  570,  583,   81,  580,  567,
      563,  569,  568,  573,   87,  568,   93,  565,  571,  564,
      567,  555,  566,  550,  548,  564,  550,  561,  564,  551,
      545,  548,  684,  544,  545,  554,  684,   87,  540,  557,
      544,  684,  543,  554,  552,  547,  533,  545,  533,  548,
       87,  542,  537,  545,  527,  533,  537,  531,  535,  534,
      533,  535,  536,   92,  522,  521,  515,  531,  522,  521,
      515,  511,  511,  511,  684,  102,  684,  509,  105,  520,

      514,  518,  507,  513,  516,  505,  504,  513,  514,  505,
      107,  504,  503,  508,  499,  505,  684,  491,  494,  503,
      486,  494,  499,  489,   95,  493,  485,  499,  475,  484,
      484,  684,  494,  491,  488,  483,  482,  684,  490,  485,
      485,  469,  465,  470,  479,  478,  464,  481,  475,  476,
      477,  684,  464,  459,  460,  684,  458,  472,  684,  464,
      459,  450,  467,  463,  443,  442,  457,  684,  684,  447,
      684,  455,  451,  452,  684,  453,  458,  457,  440,  442,
      452,  684,  450,  684,  437,  444,  451,  438,  437,  100,
      443,  437,  423,  445,  443,  426,  429,  436,  419,  426,

      430,  425,  419,  435,  684,  429,  421,  431,  426,  425,
      415,  417,  422,  421,  424,  684,  423,  412,  407,  421,
      413,  402,  415,  400,  408,  684,  684,  414,  114,  405,
      404,  393,  401,  684,  684,  684,  393,  406,  400,  403,
      406,  391,  684,  403,  398,  684,  401,  396,  395,  386,
      684,  398,  377,  382,  119,  391,  381,  380,  375,  391,
      386,  384,  378,  371,  377,  384,  371,  381,  377,  357,
      356,  368,  369,  359,  371,  380,  379,  355,  356,  358,
      684,  352,  356,  684,  361,  346,  361,  344,  104,  364,
      684,  356,  355,  358,  107,  355,  343,  347,  352,  338,

      342,  347,  339,  341,  346,  345,  338,  333,  346,  346,
      341,  340,  327,  332,  334,  322,  684,  334,  324,  684,
      684,  323,  331,  112,  330,  329,  317,  331,  330,  313,
      684,  320,  323,  318,  319,  320,  304,  309,  322,  684,
      304,  320,  316,  118,  121,  313,  316,  299,  310,  309,
      309,  296,  295,  294,  295,  303,  303,  302,  300,  297,
      286,  292,  284,  287,  285,  293,  293,  291,  274,  119,
      291,  115,  283,  284,  272,  279,  273,  277,  274,  271,
      281,  271,  684,  273,  273,  263,  264,  263,  684,  684,
      273,  272,  266,  257,  256,  684,  260,  268,  684,  684,

      684,  257,  265,  253,  267,  266,  257,  264,  252,  262,
      261,  260,  243,  258,  684,  240,  240,  232,  246,  245,
      235,  239,  235,  239,  235,  684,  684,  684,  232,  231,
      241,  238,  227,  230,  229,  239,  217,  221,  215,  228,
      233,  226,  219,  219,  229,  207,  221,  684,  684,  220,
      213,  218,  208,  220,  219,  213,  215,  214,  215,  221,
      209,  219,  211,  210,  200,  212,  199,  210,  196,  206,
      191,  207,  182,  196,  191,  187,  191,  201,  195,  183,
      684,  184,  684,  184,  196,  182,  191,  175,  181,  178,
      189,  171,  185,  173,  183,  684,  684,  176,  181,  179,

      684,  169,  163,  177,  684,  174,  177,  166,  158,  164,
      684,  166,  160,  171,  154,   29,  684,   56,  684,   78,
      684,  117,  106,  133,  124,  135,  119,  127,  123,  141,
      684,  142,  133,  684,  134,  123,  134,  147,  138,  684,
      137,  138,  129,  142,  684,  147,  144,  133,  150,  151,
      684,  136,  155,  150,  684,  157,  158,  684,  160,  142,
      162,  163,  684,  684,  684,  684,  684,  181,  182,  183
    } ;

static const flex_int16_t yy_def[671] =
    {   0,
      667,    1,  667,  667,  667,  667,  667,  668,  669,  667,
      670,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  668,  667,  669,
      667,  667,  670,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,    0,  667,  667,  667
    } ;

static const flex_int16_t yy_nxt[725] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   19,   20,    4,   21,
       22,   23,   24,    4,    4,   25,   26,   27,   28,   29,
       30,   31,   32,    4,   33,    4,    4,    4,   34,    4,
       35,   35,   35,   35,   36,   47,   50,   51,   53,   56,
      630,   54,   61,   57,   55,   66,   64,   69,   58,   67,
       62,   72,   74,   68,   83,   63,   65,  631,   73,   84,
       70,   75,   37,   48,   76,   86,   88,   77,   85,   78,
       87,   89,   35,   35,   79,   91,   92,   80,   81,   97,
      100,  111,   82,  119,  124,  101,  128,  176,  120,  632,

      208,  184,   98,  112,  129,  135,  221,  125,  136,  185,
      137,  187,  177,  209,  188,  235,  247,  222,  250,  332,
      248,  263,  264,  277,  189,  422,  278,  236,  368,  369,
      333,  251,  389,  455,  474,  428,  390,  423,  429,  476,
      502,  633,  634,  505,  475,  456,  506,  635,  636,  637,
      638,  639,  503,  477,  640,  641,  642,  643,  644,  645,
      646,  647,  648,  649,  650,  651,  652,  653,  654,  655,
      656,  657,  658,  659,  660,  661,  662,  663,  664,  665,
      666,   38,   40,   43,  629,  628,  627,  626,  625,  624,
      623,  622,  621,  620,  619,  618,  617,  616,  615,  614,

      613,  612,  611,  610,  609,  608,  607,  606,  605,  604,
      603,  602,  601,  600,  599,  598,  597,  596,  595,  594,
      593,  592,  591,  590,  589,  588,  587,  586,  585,  584,
      583,  582,  581,  580,  579,  578,  577,  576,  575,  574,
      573,  572,  571,  570,  569,  568,  567,  566,  565,  564,
      563,  562,  561,  560,  559,  558,  557,  556,  555,  554,
      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  535,  534,
      533,  532,  531,  530,  529,  528,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  516,  515,  514,

      513,  512,  511,  510,  509,  508,  507,  504,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  473,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  454,
      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  427,  426,  425,  424,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,

      399,  398,  397,  396,  395,  394,  393,  392,  391,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  249,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      186,  183,  182,  181,  180,  179,  178,  175,  174,  173,

      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  134,  133,  132,  131,  130,
      127,  126,  123,  122,  121,  118,  117,  116,  115,  114,
      113,  110,  109,  108,  107,  106,  105,  104,  103,  102,
       99,   96,   95,   94,   93,   45,   39,   41,   39,   90,
       71,   60,   59,   52,   49,   46,   45,   44,   39,   42,
       41,   39,  667,    3,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667
    } ;

static const flex_int16_t yy_chk[725] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    6,    6,    7,   15,   17,   17,   19,   20,
      616,   19,   23,   20,   19,   25,   24,   26,   20,   25,
       23,   28,   29,   25,   31,   23,   24,  618,   28,   31,
       26,   29,    7,   15,   30,   32,   33,   30,   31,   30,
       32,   33,   35,   35,   30,   44,   44,   30,   30,   54,
       56,   66,   30,   73,   77,   56,   80,  128,   73,  620,

      158,  135,   54,   66,   80,   86,  171,   77,   86,  135,
       86,  137,  128,  158,  137,  184,  196,  171,  199,  290,
      196,  211,  211,  225,  137,  389,  225,  184,  329,  329,
      290,  199,  355,  424,  444,  395,  355,  389,  395,  445,
      470,  622,  623,  472,  444,  424,  472,  624,  625,  626,
      627,  628,  470,  445,  629,  630,  632,  633,  635,  636,
      637,  638,  639,  641,  642,  643,  644,  646,  647,  648,
      649,  650,  652,  653,  654,  656,  657,  659,  660,  661,
      662,  668,  669,  670,  615,  614,  613,  612,  610,  609,
      608,  607,  606,  604,  603,  602,  600,  599,  598,  595,

      594,  593,  592,  591,  590,  589,  588,  587,  586,  585,
      584,  582,  580,  579,  578,  577,  576,  575,  574,  573,
      572,  571,  570,  569,  568,  567,  566,  565,  564,  563,
      562,  561,  560,  559,  558,  557,  556,  555,  554,  553,
      552,  551,  550,  547,  546,  545,  544,  543,  542,  541,
      540,  539,  538,  537,  536,  535,  534,  533,  532,  531,
      530,  529,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  516,  514,  513,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  498,  497,  495,  494,  493,
      492,  491,  488,  487,  486,  485,  484,  482,  481,  480,

      479,  478,  477,  476,  475,  474,  473,  471,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  443,  442,  441,  439,  438,  437,  436,  435,
      434,  433,  432,  430,  429,  428,  427,  426,  425,  423,
      422,  419,  418,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  394,  393,  392,  390,  388,  387,
      386,  385,  383,  382,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,

      364,  363,  362,  361,  360,  359,  358,  357,  356,  354,
      353,  352,  350,  349,  348,  347,  345,  344,  342,  341,
      340,  339,  338,  337,  333,  332,  331,  330,  328,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  289,  288,  287,  286,  285,  283,  281,  280,
      279,  278,  277,  276,  274,  273,  272,  270,  267,  266,
      265,  264,  263,  262,  261,  260,  258,  257,  255,  254,
      253,  251,  250,  249,  248,  247,  246,  245,  244,  243,

      242,  241,  240,  239,  237,  236,  235,  234,  233,  231,
      230,  229,  228,  227,  226,  224,  223,  222,  221,  220,
      219,  218,  216,  215,  214,  213,  212,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  198,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  170,  169,  168,  167,  166,  165,  164,  163,  161,
      160,  159,  156,  155,  154,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      136,  134,  133,  132,  131,  130,  129,  127,  126,  125,

      124,  123,  122,  121,  120,  119,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   89,   88,   87,   85,   84,   83,   82,   81,
       79,   78,   76,   75,   74,   72,   71,   70,   69,   68,
       67,   65,   64,   63,   62,   61,   60,   59,   58,   57,
       55,   53,   52,   51,   50,   45,   43,   40,   38,   34,
       27,   22,   21,   18,   16,   14,   13,   12,   11,   10,
        9,    8,    3,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config.lex.l"
#line 2 "config.lex.l"
#include <stdlib.h>
#include <string.h>
#include "wnck.h"
#include "conditional.h"
#include "statement.h"
#include "y.tab.h"

int yylinepos; // TODO: make yylinepos available in this file
#line 858 "<stdout>"
#define YY_NO_INPUT 1
#line 860 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 17 "config.lex.l"

#line 19 "config.lex.l"
 /* Actions */
 /*   cpp -P -D GENERATE_LEX_RULES "actions.gen.h" | column -t     */
#line 1080 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 668 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 684 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "config.lex.l"
return yylval.action_type=STATEMENT_CLOSE                   , ACTION_TYPE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "config.lex.l"
return yylval.action_type=STATEMENT_MINIMIZE                , ACTION_TYPE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "config.lex.l"
return yylval.action_type=STATEMENT_UNMINIMIZE              , ACTION_TYPE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "config.lex.l"
return yylval.action_type=STATEMENT_MAXIMIZE                , ACTION_TYPE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "config.lex.l"
return yylval.action_type=STATEMENT_UNMAXIMIZE              , ACTION_TYPE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "config.lex.l"
return yylval.action_type=STATEMENT_MAXIMIZE_HORIZONTALLY   , ACTION_TYPE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "config.lex.l"
return yylval.action_type=STATEMENT_UNMAXIMIZE_HORIZONTALLY , ACTION_TYPE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "config.lex.l"
return yylval.action_type=STATEMENT_MAXIMIZE_VERTICALLY     , ACTION_TYPE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "config.lex.l"
return yylval.action_type=STATEMENT_UNMAXIMIZE_VERTICALLY   , ACTION_TYPE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "config.lex.l"
return yylval.action_type=STATEMENT_SHADE                   , ACTION_TYPE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "config.lex.l"
return yylval.action_type=STATEMENT_UNSHADE                 , ACTION_TYPE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "config.lex.l"
return yylval.action_type=STATEMENT_MAKE_ABOVE              , ACTION_TYPE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "config.lex.l"
return yylval.action_type=STATEMENT_UNMAKE_ABOVE            , ACTION_TYPE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "config.lex.l"
return yylval.action_type=STATEMENT_MAKE_BELOW              , ACTION_TYPE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "config.lex.l"
return yylval.action_type=STATEMENT_UNMAKE_BELOW            , ACTION_TYPE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "config.lex.l"
return yylval.action_type=STATEMENT_STICK                   , ACTION_TYPE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "config.lex.l"
return yylval.action_type=STATEMENT_UNSTICK                 , ACTION_TYPE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "config.lex.l"
return yylval.action_type=STATEMENT_SET_SKIP_PAGER          , ACTION_TYPE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "config.lex.l"
return yylval.action_type=STATEMENT_UNSET_SKIP_PAGER        , ACTION_TYPE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "config.lex.l"
return yylval.action_type=STATEMENT_SET_SKIP_TASKLIST       , ACTION_TYPE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "config.lex.l"
return yylval.action_type=STATEMENT_UNSET_SKIP_TASKLIST     , ACTION_TYPE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "config.lex.l"
return yylval.action_type=STATEMENT_SET_FULLSCREEN          , ACTION_TYPE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "config.lex.l"
return yylval.action_type=STATEMENT_UNSET_FULLSCREEN        , ACTION_TYPE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "config.lex.l"
return yylval.action_type=STATEMENT_PIN                     , ACTION_TYPE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "config.lex.l"
return yylval.action_type=STATEMENT_UNPIN                   , ACTION_TYPE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "config.lex.l"
return yylval.action_type=STATEMENT_ACTIVATE                , ACTION_TYPE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "config.lex.l"
return yylval.action_type=STATEMENT_ACTIVATE_TRANSIENT      , ACTION_TYPE;
	YY_BREAK
/* Hook types */
case 28:
YY_RULE_SETUP
#line 50 "config.lex.l"
return yylval.hook=HOOK_OPENED                   , HOOK_TYPE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "config.lex.l"
return yylval.hook=HOOK_CLOSED                   , HOOK_TYPE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 52 "config.lex.l"
return yylval.hook=HOOK_CLASS_CHANGED            , HOOK_TYPE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 53 "config.lex.l"
return yylval.hook=HOOK_NAME_CHANGED             , HOOK_TYPE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 54 "config.lex.l"
return yylval.hook=HOOK_ROLE_CHANGED             , HOOK_TYPE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 55 "config.lex.l"
return yylval.hook=HOOK_TYPE_CHANGED             , HOOK_TYPE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 56 "config.lex.l"
return yylval.hook=HOOK_ICON_CHANGED             , HOOK_TYPE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 57 "config.lex.l"
return yylval.hook=HOOK_WORKSPACE_CHANGED        , HOOK_TYPE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 58 "config.lex.l"
return yylval.hook=HOOK_STATE_CHANGED            , HOOK_TYPE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "config.lex.l"
return yylval.hook=HOOK_WINDOW_STACKING_CHANGED  , HOOK_TYPE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "config.lex.l"
return yylval.hook=HOOK_ACTIVE_WORKSPACE_CHANGED , HOOK_TYPE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "config.lex.l"
return yylval.hook=HOOK_SHOWING_DESKTOP_CHANGED  , HOOK_TYPE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_MINIMIZED              , WINDOW_STATE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_MAXIMIZED_HORIZONTALLY , WINDOW_STATE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_MAXIMIZED_VERTICALLY   , WINDOW_STATE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_SHADED                 , WINDOW_STATE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_SKIP_PAGER             , WINDOW_STATE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_SKIP_TASKLIST          , WINDOW_STATE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_HIDDEN                 , WINDOW_STATE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_FULLSCREEN             , WINDOW_STATE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_DEMANDS_ATTENTION      , WINDOW_STATE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_ABOVE                  , WINDOW_STATE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_BELOW                  , WINDOW_STATE;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_INACTIVE_WORKSPACE     , WINDOW_STATE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "config.lex.l"
return yylval.state=WNCK_WINDOW_STATE_STICKY                 , WINDOW_STATE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 77 "config.lex.l"
return yylval.type=WNCK_WINDOW_DESKTOP      , WINDOW_TYPE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 "config.lex.l"
return yylval.type=WNCK_WINDOW_DIALOG       , WINDOW_TYPE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 "config.lex.l"
return yylval.type=WNCK_WINDOW_DOCK         , WINDOW_TYPE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 "config.lex.l"
return yylval.type=WNCK_WINDOW_MENU         , WINDOW_TYPE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 "config.lex.l"
return yylval.type=WNCK_WINDOW_NORMAL       , WINDOW_TYPE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 "config.lex.l"
return yylval.type=WNCK_WINDOW_SPLASHSCREEN , WINDOW_TYPE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 "config.lex.l"
return yylval.type=WNCK_WINDOW_TOOLBAR      , WINDOW_TYPE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 "config.lex.l"
return yylval.type=WNCK_WINDOW_UTILITY      , WINDOW_TYPE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "config.lex.l"
return yylval.field=WINDOW_TITLE     , WINDOW_FIELD;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 87 "config.lex.l"
return yylval.field=WINDOW_GROUP     , WINDOW_FIELD;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 88 "config.lex.l"
return yylval.field=WINDOW_CLASS     , WINDOW_FIELD;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 89 "config.lex.l"
return yylval.field=WINDOW_ICON_NAME , WINDOW_FIELD;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 90 "config.lex.l"
return yylval.field=WINDOW_ROLE      , WINDOW_FIELD;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "config.lex.l"
return yylval.field=WINDOW_WORKSPACE , WINDOW_FIELD;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "config.lex.l"
return COND_WORKSPACE_NUMBER;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "config.lex.l"
return COND_TYPE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "config.lex.l"
return COND_STACKPOSITION;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 95 "config.lex.l"
return COND_STATE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 96 "config.lex.l"
return COND_HOOK;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "config.lex.l"
return PRINT;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "config.lex.l"
return SYSTEM;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 100 "config.lex.l"
return RETURN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 101 "config.lex.l"
return SUSPEND;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 102 "config.lex.l"
return PROCESS;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 103 "config.lex.l"
return CHILDREN;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 104 "config.lex.l"
return HAS;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 105 "config.lex.l"
return OPTION_SUSPEND_DELAY;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 106 "config.lex.l"
return OPTION_REFRESH_DELAY;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 107 "config.lex.l"
return OPTION_REFRESH_DURATION;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "config.lex.l"
return yylval.comparison=COMPARE_EQUAL         , EQUAL;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "config.lex.l"
return yylval.comparison=COMPARE_UNEQUAL       , UNEQUAL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 111 "config.lex.l"
return yylval.comparison=COMPARE_GREATER       , GREATER;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 112 "config.lex.l"
return yylval.comparison=COMPARE_GREATER_EQUAL , GREATER_EQUAL;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "config.lex.l"
return yylval.comparison=COMPARE_LESS          , LESS;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 114 "config.lex.l"
return yylval.comparison=COMPARE_LESS_EQUAL    , LESS_EQUAL;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 115 "config.lex.l"
return /* --------------------------------- */   REGEX_EQUAL;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 116 "config.lex.l"
return /* --------------------------------- */   REGEX_UNEQUAL;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 117 "config.lex.l"
return /* --------------------------------- */   CONTAINS;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 119 "config.lex.l"
return NOT;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 120 "config.lex.l"
return AND_AND;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 121 "config.lex.l"
return OR_OR;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 123 "config.lex.l"
return yylval.number=atoi(yytext), NUMBER;
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 124 "config.lex.l"
return yylval.string=strdup(yytext+1), yylval.string[yyleng-2]='\0', STRING;
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 126 "config.lex.l"
/* ignore comments */;
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 127 "config.lex.l"
/* ignore whitespace */;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 129 "config.lex.l"
return yytext[0];
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 130 "config.lex.l"
ECHO;
	YY_BREAK
#line 1646 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 668 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 668 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 667);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 130 "config.lex.l"


